/*Статья https://info-comp.ru/sequence-in-microsoft-sql-server*/

CREATE SEQUENCE TestSequence;

DROP SEQUENCE TestSequence

CREATE SEQUENCE TestSequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TestSequence
START WITH 10
INCREMENT BY 5;

CREATE SEQUENCE TestSequence
START WITH 0
INCREMENT BY -1;

CREATE SEQUENCE TestSequence
START WITH 12345
INCREMENT BY 1;

CREATE SEQUENCE TestSequence
AS TINYINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TestSequence
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50;

CREATE SEQUENCE TestSequence
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50
CYCLE;

ALTER SEQUENCE TestSequence
RESTART WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 50;

ALTER SEQUENCE TestSequence
RESTART WITH 1;

SELECT NEXT VALUE FOR TestSequence;
SELECT NEXT VALUE FOR TestSequence;
SELECT NEXT VALUE FOR TestSequence;

CREATE TABLE Goods
(
	ProductId INT NOT NULL,
	ProductName VARCHAR(100) NOT NULL
);

INSERT INTO Goods
VALUES (NEXT VALUE FOR TestSequence, 'Компьютер'),
	   (NEXT VALUE FOR TestSequence, 'Монитор'),
	   (NEXT VALUE FOR TestSequence, 'Клавиатура')

SELECT *
FROM Goods

DROP SEQUENCE IF EXISTS TestSequence